on: [push, workflow_dispatch]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Preparing git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'

      - name: Installing
        run: yarn install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Testing
        run: yarn test

      - name: Publishing
        run:
          yarn release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Saving yarn.lock
        run: |
          mv yarn.lock yarn-ci.lock
          if [ -z "$(git status --porcelain)" ]; then
            echo "yarn.lock wasn't changed"
          else
            # commiting the file
            git add yarn.lock
            git commit -m "chore(yarn.lock): updated [ci skip]"
            git push https://${{ secrets.GITHUB_TOKEN }}@github.com/slavhsik/logger-that-i-use.git
          fi
